<?php

$username = $form->get('alternate_id');
$username->setAttribute('class', 'form-control')
    ->setAttribute('id', 'inlineFormInputGroup')
    ->setLabelAttributes([
            'class' => 'control-label'
    ]);

$password = $form->get('password');
$password->setAttribute('class', 'form-control')
    ->setLabelAttributes(['class' => 'control-label']);

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-emporium');

$form->setAttribute('action', $this->url('login'));
$form->prepare();
?>

<?php if ($messageError): ?>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span>
        </button>
        <strong>Erro!</strong> <?= $messageError; ?>
    </div>
<?php endif; ?>

<div class="row col-md-6 col-md-offset-3 tleft">
    <div class="col-md-4 col-md-offset-4">
        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($username); ?>

            <div style="margin-bottom: 25px" class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                <?= $this->formElement($username); ?>
            </div>
        </div>

        <div class="form-group">
            <?= $this->formLabel($password); ?>

            <div style="margin-bottom: 25px" class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                <?= $this->formElement($password); ?>
            </div>
        </div>

        <div class="form-group" align="center">
            <?= $this->formSubmit($submit); ?>
        </div>

        <?php
        echo $this->form()->closeTag();
        ?>
    </div>
</div>