<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Emporium')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->appendStylesheet('css/bootstrap.min.css') // bootstrap
        ->appendStylesheet('css/font-awesome.min.css') // fontawesome
        ->appendStylesheet('css/fonts.googleapis.com.css') // text fonts
        ->appendStylesheet($this->basePath('css/ace.min.css'),
            'screen',
            false,
            array(
                'class' => 'ace-main-stylesheet',
                'id' => 'main-ace-style'
            )
        ) //ace styles
        ->appendStylesheet($this->basePath('css/ace-part2.min.css'),
            'screen',
            'lte IE 9',
            array(
                'class' => 'ace-main-stylesheet'
            )
        ) //ace styles
        ->appendStylesheet($this->basePath('css/ace-skins.min.css'))
        ->appendStylesheet($this->basePath('css/ace-rtl.min.css'))
        ->appendStylesheet($this->basePath('css/ace-ie.min.css'),
            'screen',
            'lte IE 9'
        ) //ace styles
        ->appendStylesheet($this->basePath('css/style-menu.css'))
    ?>

    <!-- Scripts Head-->
    <?= $this->headScript()
        ->appendFile($this->basePath('js/ace-extra.min.js')) // ace settings handler
        ->appendFile($this->basePath('js/html5shiv.min.js'),'text/javascript',
            array(
                'conditional' => 'IE 8'
            )
        )

    ?>

</head>

<body class="no-skin">

<div class="main-container ace-save-state" id="main-container">
    <script type="text/javascript">
        try{ace.settings.loadState('main-container')}catch(e){}
    </script>

    <div id="sidebar" class="sidebar h-sidebar navbar-collapse collapse ace-save-state top-div">
        <script type="text/javascript">
            try{ace.settings.loadState('sidebar')}catch(e){}
        </script>

        <div class="navbar-header pull-left top-div">
            <a href="index.html" class="navbar-brand">
                <small>
                    <img src="<?= $this->basePath() . '/img/logo-top.png';?>" class="img-responsive img-logo">

                </small>
            </a>
        </div>

        <ul class="nav nav-list">
            <li class="hover">
                <a href="index.html">
                    <i class="menu-icon fa fa-tachometer"></i>
                    <span class="menu-text"> Dashboard </span>
                </a>

                <b class="arrow"></b>
            </li>

            <li class="active open hover">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-desktop"></i>
                    <span class="menu-text">
                UI &amp; Elements
              </span>

                    <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                    <li class="active open hover">
                        <a href="#" class="dropdown-toggle">
                            <i class="menu-icon fa fa-caret-right"></i>

                            Layouts
                            <b class="arrow fa fa-angle-down"></b>
                        </a>

                        <b class="arrow"></b>

                        <ul class="submenu">
                            <li class="hover">
                                <a href="top-menu.html">
                                    <i class="menu-icon fa fa-caret-right"></i>
                                    Top Menu
                                </a>

                                <b class="arrow"></b>
                            </li>

                            <li class="hover">
                                <a href="two-menu-1.html">
                                    <i class="menu-icon fa fa-caret-right"></i>
                                    Two Menus 1
                                </a>

                                <b class="arrow"></b>
                            </li>

                            <li class="active hover">
                                <a href="two-menu-2.html">
                                    <i class="menu-icon fa fa-caret-right"></i>
                                    Two Menus 2
                                </a>

                                <b class="arrow"></b>
                            </li>

                            <li class="hover">
                                <a href="mobile-menu-1.html">
                                    <i class="menu-icon fa fa-caret-right"></i>
                                    Default Mobile Menu
                                </a>

                                <b class="arrow"></b>
                            </li>

                            <li class="hover">
                                <a href="mobile-menu-2.html">
                                    <i class="menu-icon fa fa-caret-right"></i>
                                    Mobile Menu 2
                                </a>

                                <b class="arrow"></b>
                            </li>

                            <li class="hover">
                                <a href="mobile-menu-3.html">
                                    <i class="menu-icon fa fa-caret-right"></i>
                                    Mobile Menu 3
                                </a>

                                <b class="arrow"></b>
                            </li>
                        </ul>
                    </li>

                    <li class="hover">
                        <a href="typography.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Typography
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="elements.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Elements
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="buttons.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Buttons &amp; Icons
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="content-slider.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Content Sliders
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="treeview.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Treeview
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="jquery-ui.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            jQuery UI
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="nestable-list.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Nestable Lists
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="#" class="dropdown-toggle">
                            <i class="menu-icon fa fa-caret-right"></i>

                            Three Level Menu
                            <b class="arrow fa fa-angle-down"></b>
                        </a>

                        <b class="arrow"></b>

                        <ul class="submenu">
                            <li class="hover">
                                <a href="#">
                                    <i class="menu-icon fa fa-leaf green"></i>
                                    Item #1
                                </a>

                                <b class="arrow"></b>
                            </li>

                            <li class="hover">
                                <a href="#" class="dropdown-toggle">
                                    <i class="menu-icon fa fa-pencil orange"></i>

                                    4th level
                                    <b class="arrow fa fa-angle-down"></b>
                                </a>

                                <b class="arrow"></b>

                                <ul class="submenu">
                                    <li class="hover">
                                        <a href="#">
                                            <i class="menu-icon fa fa-plus purple"></i>
                                            Add Product
                                        </a>

                                        <b class="arrow"></b>
                                    </li>

                                    <li class="hover">
                                        <a href="#">
                                            <i class="menu-icon fa fa-eye pink"></i>
                                            View Products
                                        </a>

                                        <b class="arrow"></b>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>

            <li class="hover">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-list"></i>
                    <span class="menu-text"> Tables </span>

                    <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                    <li class="hover">
                        <a href="tables.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Simple &amp; Dynamic
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="jqgrid.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            jqGrid plugin
                        </a>

                        <b class="arrow"></b>
                    </li>
                </ul>
            </li>

            <li class="hover">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-pencil-square-o"></i>
                    <span class="menu-text"> Forms </span>

                    <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                    <li class="hover">
                        <a href="form-elements.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Form Elements
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="form-elements-2.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Form Elements 2
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="form-wizard.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Wizard &amp; Validation
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="wysiwyg.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Wysiwyg &amp; Markdown
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="dropzone.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Dropzone File Upload
                        </a>

                        <b class="arrow"></b>
                    </li>
                </ul>
            </li>

            <li class="hover">
                <a href="widgets.html">
                    <i class="menu-icon fa fa-list-alt"></i>
                    <span class="menu-text"> Widgets </span>
                </a>

                <b class="arrow"></b>
            </li>

            <li class="hover">
                <a href="calendar.html">
                    <i class="menu-icon fa fa-calendar"></i>

                    <span class="menu-text">
                Calendar

                <span class="badge badge-transparent tooltip-error" title="2 Important Events">
                  <i class="ace-icon fa fa-exclamation-triangle red bigger-130"></i>
                </span>
              </span>
                </a>

                <b class="arrow"></b>
            </li>

            <li class="hover">
                <a href="gallery.html">
                    <i class="menu-icon fa fa-picture-o"></i>
                    <span class="menu-text"> Gallery </span>
                </a>

                <b class="arrow"></b>
            </li>

            <li class="hover">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-tag"></i>
                    <span class="menu-text"> More Pages </span>

                    <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                    <li class="hover">
                        <a href="profile.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            User Profile
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="inbox.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Inbox
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="pricing.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Pricing Tables
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="invoice.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Invoice
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="timeline.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Timeline
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="search.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Search Results
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="email.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Email Templates
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="login.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Login &amp; Register
                        </a>

                        <b class="arrow"></b>
                    </li>
                </ul>
            </li>

            <li class="hover">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-file-o"></i>

                    <span class="menu-text">
                Other Pages

                <span class="badge badge-primary">5</span>
              </span>

                    <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                    <li class="hover">
                        <a href="faq.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            FAQ
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="error-404.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Error 404
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="error-500.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Error 500
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="grid.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Grid
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="hover">
                        <a href="blank.html">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Blank Page
                        </a>

                        <b class="arrow"></b>
                    </li>
                </ul>
            </li>
        </ul><!-- /.nav-list -->
    </div>

    <div class="main-content">
        <div class="main-content-inner">
            <div class="page-content">
                <div class="ace-settings-container" id="ace-settings-container">
                    <div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
                        <i class="ace-icon fa fa-cog bigger-130"></i>
                    </div>

                    <div class="ace-settings-box clearfix" id="ace-settings-box">
                        <div class="pull-left width-50">
                            <div class="ace-settings-item">
                                <div class="pull-left">
                                    <select id="skin-colorpicker" class="hide">
                                        <option data-skin="no-skin" value="#438EB9">#438EB9</option>
                                        <option data-skin="skin-1" value="#222A2D">#222A2D</option>
                                        <option data-skin="skin-2" value="#C6487E">#C6487E</option>
                                        <option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
                                    </select>
                                </div>
                                <span>&nbsp; Choose Skin</span>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-navbar" autocomplete="off" />
                                <label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-sidebar" autocomplete="off" />
                                <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-breadcrumbs" autocomplete="off" />
                                <label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl" autocomplete="off" />
                                <label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-add-container" autocomplete="off" />
                                <label class="lbl" for="ace-settings-add-container">
                                    Inside
                                    <b>.container</b>
                                </label>
                            </div>
                        </div><!-- /.pull-left -->

                        <div class="pull-left width-50">
                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-hover" autocomplete="off" />
                                <label class="lbl" for="ace-settings-hover"> Submenu on Hover</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-compact" autocomplete="off" />
                                <label class="lbl" for="ace-settings-compact"> Compact Sidebar</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-highlight" autocomplete="off" />
                                <label class="lbl" for="ace-settings-highlight"> Alt. Active Item</label>
                            </div>
                        </div><!-- /.pull-left -->
                    </div><!-- /.ace-settings-box -->
                </div><!-- /.ace-settings-container -->

                <div class="page-header">
                    <h1>Two Menu Style </h1>
                </div><!-- /.page-header -->

                <div class="row">
                    <div class="col-xs-12">
                        <!-- PAGE CONTENT BEGINS -->
                        <div class="invisible">
                            <button data-target="#sidebar2" type="button" class="pull-left menu-toggler navbar-toggle">
                                <span class="sr-only">Toggle sidebar</span>

                                <i class="ace-icon fa fa-dashboard white bigger-125"></i>
                            </button>

                            <div id="sidebar2" class="sidebar responsive menu-min ace-save-state">
                                <ul class="nav nav-list">
                                    <li>
                                        <a href="#">
                                            <i class="menu-icon fa fa-tachometer"></i>
                                            <span class="menu-text"> Dashboard </span>
                                        </a>

                                        <b class="arrow"></b>
                                    </li>

                                    <li>
                                        <a href="#">
                                            <i class="menu-icon fa fa-list-alt"></i>
                                            <span class="menu-text">Widgets</span>
                                        </a>

                                        <b class="arrow"></b>
                                    </li>

                                    <li>
                                        <a href="#">
                                            <i class="menu-icon fa fa-calendar"></i>

                                            <span class="menu-text">
                            Calendar
                            <span title="" class="badge badge-transparent tooltip-error" data-original-title="2 Important Events">
                              <i class="ace-icon fa fa-exclamation-triangle red bigger-130"></i>
                            </span>
                          </span>
                                        </a>

                                        <b class="arrow"></b>
                                    </li>

                                    <li>
                                        <a href="#">
                                            <i class="menu-icon fa fa-picture-o"></i>
                                            <span class="menu-text"> Gallery </span>
                                        </a>

                                        <b class="arrow"></b>
                                    </li>

                                    <li>
                                        <a class="dropdown-toggle" href="#">
                                            <i class="menu-icon fa fa-tag"></i>
                                            <span class="menu-text"> More Pages </span>

                                            <b class="arrow fa fa-angle-down"></b>
                                        </a>

                                        <b class="arrow"></b>

                                        <ul class="submenu">
                                            <li>
                                                <a href="#">
                                                    <i class="menu-icon fa fa-caret-right"></i>
                                                    User Profile
                                                </a>

                                                <b class="arrow"></b>
                                            </li>

                                            <li>
                                                <a href="#">
                                                    <i class="menu-icon fa fa-caret-right"></i>
                                                    Inbox
                                                </a>

                                                <b class="arrow"></b>
                                            </li>

                                            <li>
                                                <a href="#">
                                                    <i class="menu-icon fa fa-caret-right"></i>
                                                    Pricing Tables
                                                </a>

                                                <b class="arrow"></b>
                                            </li>

                                            <li>
                                                <a href="#">
                                                    <i class="menu-icon fa fa-caret-right"></i>
                                                    Invoice
                                                </a>

                                                <b class="arrow"></b>
                                            </li>

                                            <li>
                                                <a href="#">
                                                    <i class="menu-icon fa fa-caret-right"></i>
                                                    Timeline
                                                </a>

                                                <b class="arrow"></b>
                                            </li>

                                            <li>
                                                <a href="#">
                                                    <i class="menu-icon fa fa-caret-right"></i>
                                                    Email Templates
                                                </a>

                                                <b class="arrow"></b>
                                            </li>

                                            <li>
                                                <a href="#">
                                                    <i class="menu-icon fa fa-caret-right"></i>
                                                    Login &amp; Register
                                                </a>

                                                <b class="arrow"></b>
                                            </li>
                                        </ul>
                                    </li>

                                    <li>
                                        <a class="dropdown-toggle" href="#">
                                            <i class="menu-icon fa fa-file-o"></i>

                                            <span class="menu-text">
                            Other Pages
                            <span class="badge badge-primary">5</span>
                          </span>

                                            <b class="arrow fa fa-angle-down"></b>
                                        </a>

                                        <b class="arrow"></b>

                                        <ul class="submenu">
                                            <li>
                                                <a href="#">
                                                    <i class="menu-icon fa fa-caret-right"></i>
                                                    FAQ
                                                </a>

                                                <b class="arrow"></b>
                                            </li>

                                            <li>
                                                <a href="#">
                                                    <i class="menu-icon fa fa-caret-right"></i>
                                                    Error 404
                                                </a>

                                                <b class="arrow"></b>
                                            </li>

                                            <li>
                                                <a href="#">
                                                    <i class="menu-icon fa fa-caret-right"></i>
                                                    Error 500
                                                </a>

                                                <b class="arrow"></b>
                                            </li>

                                            <li>
                                                <a href="#">
                                                    <i class="menu-icon fa fa-caret-right"></i>
                                                    Grid
                                                </a>

                                                <b class="arrow"></b>
                                            </li>

                                            <li>
                                                <a href="#">
                                                    <i class="menu-icon fa fa-caret-right"></i>
                                                    Blank Page
                                                </a>

                                                <b class="arrow"></b>
                                            </li>
                                        </ul>
                                    </li>
                                </ul><!-- /.nav-list -->

                                <div class="sidebar-toggle sidebar-collapse">
                                    <i id="sidebar3-toggle-icon" class="ace-icon fa fa-angle-double-right ace-save-state" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
                                </div>
                            </div><!-- .sidebar -->
                        </div>

                        <div class="hidden-sm hidden-xs">
                            <button type="button" class="sidebar-collapse btn btn-white btn-primary" data-target="#sidebar">
                                <i id="sidebar4-toggle-icon" class="ace-icon fa fa-angle-double-up ace-save-state" data-icon1="ace-icon fa fa-angle-double-up" data-icon2="ace-icon fa fa-angle-double-down"></i>
                                Collapse/Expand Menu
                            </button>
                        </div>

                        <!-- PAGE CONTENT ENDS -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->

<!--    <div class="footer">-->
<!--        <div class="footer-inner">-->
<!--            <div class="footer-content">-->
<!--                <span class="bigger-120">-->
<!--                  Emporium &copy; --><?//= date("Y") ?>
<!--                </span>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
    </a>
</div><!-- /.main-container -->

<!-- basic scripts -->
<!--Script footer-->
<?= $this->inlineScript()
    ->appendFile($this->basePath('js/jquery-2.1.4.min.js'),'text/javascript',
        array(
            'conditional' => '!IE'
        )
    )
    ->appendFile($this->basePath('js/jquery-1.11.3.min.js'),'text/javascript',
        array(
            'conditional' => 'IE'
        )
    )
?>

<script type="text/javascript">
    if('ontouchstart' in document.documentElement) document.write("<script src='js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
</script>

<?= $this->inlineScript()
        ->appendFile('js/bootstrap.min.js')
        ->appendFile('js/ace-elements.min.js')
        ->appendFile('js/ace.min.js')
        ->appendFile('js/ace-script-menu.js')
?>

</body>
</html>
