<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Emporium Login')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
    ?>
</head>

<body>

<div class="navbar navbar-fixed-top login-banner">
    <div class="col-md-12">
        <img src="<?= $this->basePath() . '/img/logo-login.jpg';?>"
             class="img-responsive" align="center">
    </div>
</div>

<div class="container margin-top" >
    <?= $this->content; ?>
</div>

<div class="container" >
    <hr>

    <footer class="navbar">
        <p>&copy; 2018 by Conecto Sistemas. All rights reserved.</p>
    </footer>
</div>

<?= $this->inlineScript() ?>

</body>

</html>
